### PR TITLE
Add support for terraform block in markdown files

### LINKED ISSUE #177: Enable markdown code block support
VS Code supports tagging of code blocks in markdown to enable colorization, but this isn't currently working for terraform.

E.g. the following gets colorized

    ```javascript
    var wibble = 'testing'
    ```

But an equivalent terraform codeblock doesn't

    ```terraform
    resource "test" "foo" {
        "foo" = "bar"
        "name" = "${var.name}"
    }
    ```

### PR DESCRIPTION
**Pull request by stuartleeks**
Closes #177

### CODE REVIEW

**Comment by mauve** [comment]
cool, thanks!

I will try to make a new release this week.

**Comment by stuartleeks** [comment]
You're welcome - thanks for the great extension!

Look forward to the new release :-D

**Comment by stuartleeks** [comment]
@mauve - just wondered if you had any update on when you might release this? I have a temporary extension that adds this support in addition to your extension but would love to deprecate that :-)

**Comment by mauve** [comment]
sorry for the delay, will do it this weekend.

you seem to know what you are doing, would be awesome if you could lend a
hand in https://github.com/mauve/vscode-terraform/issues/157 :)

/M

**Comment by stuartleeks** [comment]
@mauve - I took a look at that issue, but honestly think I'm out of my depth on both the HCL2 side and the VSCode integration side :-(

**Pull request merged**
