### PR TITLE
Terraform auto completion support

### PR DESCRIPTION
**Pull request by ranga543**
1. `Terraform` high level types `(variable, resource, data, module ...)` auto completion support.
2. `resource` types `(aws_dynamodb_table ...)` auto completion support for `aws, azure & google`
3. `resource | data | module | output | variable` property types auto completion support
4. `resource | data` 1-level nested block property types auto completion support

### CODE REVIEW

**Comment by mauve** [comment]
really cool, thanks

**Comment by mauve** [comment]
how did you generate the JSON files with the data in it btw?

**Comment by ranga543** [comment]
I created [this](https://github.com/ranga543/terraform-docs-scrape) project which will generate the `json` files for providers.

**Comment by mauve** [comment]
cool, I added a quick note in the source code about it so that I can find it again.

**Pull request merged**
